
trigger:
- main123

pool: ravinewpool

stages:
- stage: Build
  displayName: Build the docker image
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'aarviaahanaacrdevopsconnection'
        repository: 'sampleimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags:
          $(Build.BuildId)
    - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)
    - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -al $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'
    - bash: echo $(Pipeline.Workspace)
    - bash: ls -al $(Pipeline.Workspace)
